--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: skiapp-deployment
  namespace: team-riker
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: skiapp
  template: 
    metadata: 
      labels: 
        app: skiapp
    spec: 
      containers: 
        - 
          image: "sharepointoscar/skiapp:v2"
          name: skiapp
          ports: 
            - 
              containerPort: 8080
          resources: 
            limits: 
              memory: 128Mi
              cpu: 500m
            requests: 
              cpu: 250m
              memory: 64Mi
